version: 2

build:
  tools:
    python: "3.10"

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false


python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - lite