# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.2.3.dev102+g9e191ca.d20211113'
version_tuple = (0, 2, 3, 'dev102', 'g9e191ca.d20211113')
